// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeExtension(arg1) {
  return window['go']['main']['App']['ChangeExtension'](arg1);
}

export function GetClipText() {
  return window['go']['main']['App']['GetClipText']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRunHistory() {
  return window['go']['main']['App']['GetRunHistory']();
}

export function GoogleTranslate(arg1, arg2, arg3) {
  return window['go']['main']['App']['GoogleTranslate'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function InstallExtension(arg1) {
  return window['go']['main']['App']['InstallExtension'](arg1);
}

export function ListApplications() {
  return window['go']['main']['App']['ListApplications']();
}

export function ListExtension(arg1) {
  return window['go']['main']['App']['ListExtension'](arg1);
}

export function ListInstalled() {
  return window['go']['main']['App']['ListInstalled']();
}

export function RunApplication(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunApplication'](arg1, arg2, arg3, arg4);
}

export function SetClipText(arg1) {
  return window['go']['main']['App']['SetClipText'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function ToBlur() {
  return window['go']['main']['App']['ToBlur']();
}

export function ToFocus() {
  return window['go']['main']['App']['ToFocus']();
}
