// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function Hide():Promise<void>;

export function ListApplications():Promise<Array<any>>;

export function RunApplication(arg1:string):Promise<void>;

export function Show():Promise<void>;

export function ToBlur():Promise<void>;

export function ToFocus():Promise<void>;
